---
all:
  children:
   aarch64:
    hosts:
#     foss-uk-builder1:
#      ansible_host: 2a09:11c0:337:fff6::2
#     foss-bos-builder1:
#      ansible_host: 2a09:11c0:333:fff6::2
#     foss-uk-builder2:
#      ansible_host: 2a09:11c0:336:fff5::2
#     oracle-builder1:
#      ansible_host: 2603:c022:c002:4800::20
#      ansible_user: ubuntu
     openstack-builder1:
      ansible_host: 140.211.169.12
      ansible_user: gentoo
     openstack-builder2:
      ansible_host: 140.211.169.52
      ansible_user: gentoo
     openstack-builder3:
      ansible_host: 140.211.169.38
      ansible_user: gentoo

